#############################################################################
# Makefile for building: Helios
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  helios.pro
# Template: app
# Command: /Users/Toby/Qt5.2.1/5.2.1/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile helios.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT5BUILD -DDARWIN -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -gdwarf-2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -msse -msse2 -msse3 -arch x86_64 -g -gdwarf-2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -Wall -W -Wno-unused-parameter -fPIE $(DEFINES)
INCPATH       = -I/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/macx-clang -I. -Iinclude -I/usr/local/include -I/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtOpenGL.framework/Versions/5/Headers -I/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers -I/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers -Imoc -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -F/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS) -F/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib -L/usr/local/lib -framework QtOpenGL -framework QtWidgets -framework QtGui -framework QtCore -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Users/Toby/Qt5.2.1/5.2.1/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/main.cpp \
		src/mainwindow.cpp \
		src/Camera.cpp \
		src/OpenGLWidget.cpp moc/moc_mainwindow.cpp \
		moc/moc_OpenGLWidget.cpp
OBJECTS       = obj/main.o \
		obj/mainwindow.o \
		obj/Camera.o \
		obj/OpenGLWidget.o \
		obj/moc_mainwindow.o \
		obj/moc_OpenGLWidget.o
DIST          = /Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/spec_pre.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/qdevice.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/device_config.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/common/shell-unix.conf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/common/unix.conf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/common/mac.conf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/common/macx.conf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/common/gcc-base.conf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/common/clang.conf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/common/clang-mac.conf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/qconfig.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/qt_functions.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/qt_config.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.cache \
		.qmake.stash \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/default_pre.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/resolve_config.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/default_post.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/qml_debug.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/declarative_debug.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/warn_on.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/qt.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/resources.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/moc.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/uic.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/unix/thread.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/rez.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/exceptions.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/yacc.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/lex.prf \
		helios.pro \
		helios.pro
QMAKE_TARGET  = Helios
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Helios

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk \
		-mmacosx-version-min=10.6 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: helios.pro .qmake.cache /Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/macx-clang/qmake.conf /Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/spec_pre.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/qdevice.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/device_config.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/common/shell-unix.conf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/common/unix.conf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/common/mac.conf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/common/macx.conf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/common/gcc-base.conf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/common/clang.conf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/common/clang-mac.conf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/qconfig.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/qt_functions.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/qt_config.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.cache \
		.qmake.stash \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/default_pre.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/resolve_config.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/default_post.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/qml_debug.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/declarative_debug.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/warn_on.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/qt.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/resources.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/moc.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/uic.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/unix/thread.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/rez.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/exceptions.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/yacc.prf \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/lex.prf \
		helios.pro \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile helios.pro
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/spec_pre.prf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/qdevice.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/device_config.prf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/common/shell-unix.conf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/common/unix.conf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/common/mac.conf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/common/macx.conf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/common/gcc-base.conf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/common/gcc-base-mac.conf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/common/clang.conf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/common/clang-mac.conf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/qconfig.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_core.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_help.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_network.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_script.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/qt_functions.prf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/qt_config.prf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/macx-clang/qmake.conf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/spec_post.prf:
.qmake.cache:
.qmake.stash:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/exclusive_builds.prf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/default_pre.prf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/default_pre.prf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/resolve_config.prf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/default_post.prf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/sdk.prf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/default_post.prf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/objective_c.prf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/qml_debug.prf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/declarative_debug.prf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/warn_on.prf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/qt.prf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/resources.prf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/moc.prf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/unix/opengl.prf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/uic.prf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/unix/thread.prf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/rez.prf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/testcase_targets.prf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/exceptions.prf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/yacc.prf:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/mkspecs/features/lex.prf:
helios.pro:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile helios.pro

qmake_all: FORCE

dist: 
	@test -d obj/Helios1.0.0 || mkdir -p obj/Helios1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/Helios1.0.0/ && $(COPY_FILE) --parents include/mainwindow.h include/Camera.h include/OpenGLWidget.h obj/Helios1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/mainwindow.cpp src/Camera.cpp src/OpenGLWidget.cpp obj/Helios1.0.0/ && $(COPY_FILE) --parents ui/mainwindow.ui obj/Helios1.0.0/ && (cd `dirname obj/Helios1.0.0` && $(TAR) Helios1.0.0.tar Helios1.0.0 && $(COMPRESS) Helios1.0.0.tar) && $(MOVE) `dirname obj/Helios1.0.0`/Helios1.0.0.tar.gz . && $(DEL_FILE) -r obj/Helios1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc/moc_mainwindow.cpp moc/moc_OpenGLWidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_mainwindow.cpp moc/moc_OpenGLWidget.cpp
moc/moc_mainwindow.cpp: /Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QToolBar \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbar.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QToolButton \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbutton.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDockWidget \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdockwidget.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenuBar \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QComboBox \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcombobox.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGridLayout \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgridlayout.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QSpacerItem \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlayoutitem.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QColorDialog \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolordialog.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPushButton \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDoubleSpinBox \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qspinbox.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGroupBox \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgroupbox.h \
		include/OpenGLWidget.h \
		include/Camera.h \
		/usr/local/include/glm/glm.hpp \
		/usr/local/include/glm/detail/_fixes.hpp \
		/usr/local/include/glm/fwd.hpp \
		/usr/local/include/glm/detail/type_int.hpp \
		/usr/local/include/glm/detail/setup.hpp \
		/usr/local/include/glm/detail/type_float.hpp \
		/usr/local/include/glm/detail/type_vec.hpp \
		/usr/local/include/glm/detail/precision.hpp \
		/usr/local/include/glm/detail/type_mat.hpp \
		/usr/local/include/glm/vec2.hpp \
		/usr/local/include/glm/detail/type_vec2.hpp \
		/usr/local/include/glm/detail/_swizzle.hpp \
		/usr/local/include/glm/detail/_swizzle_func.hpp \
		/usr/local/include/glm/detail/type_vec2.inl \
		/usr/local/include/glm/vec3.hpp \
		/usr/local/include/glm/detail/type_vec3.hpp \
		/usr/local/include/glm/detail/type_vec3.inl \
		/usr/local/include/glm/vec4.hpp \
		/usr/local/include/glm/detail/type_vec4.hpp \
		/usr/local/include/glm/detail/type_vec4.inl \
		/usr/local/include/glm/mat2x2.hpp \
		/usr/local/include/glm/detail/type_mat2x2.hpp \
		/usr/local/include/glm/detail/type_mat2x2.inl \
		/usr/local/include/glm/mat2x3.hpp \
		/usr/local/include/glm/detail/type_mat2x3.hpp \
		/usr/local/include/glm/detail/type_mat2x3.inl \
		/usr/local/include/glm/mat2x4.hpp \
		/usr/local/include/glm/detail/type_mat2x4.hpp \
		/usr/local/include/glm/detail/type_mat2x4.inl \
		/usr/local/include/glm/mat3x2.hpp \
		/usr/local/include/glm/detail/type_mat3x2.hpp \
		/usr/local/include/glm/detail/type_mat3x2.inl \
		/usr/local/include/glm/mat3x3.hpp \
		/usr/local/include/glm/detail/type_mat3x3.hpp \
		/usr/local/include/glm/detail/type_mat3x3.inl \
		/usr/local/include/glm/mat3x4.hpp \
		/usr/local/include/glm/detail/type_mat3x4.hpp \
		/usr/local/include/glm/detail/type_mat3x4.inl \
		/usr/local/include/glm/mat4x2.hpp \
		/usr/local/include/glm/detail/type_mat4x2.hpp \
		/usr/local/include/glm/detail/type_mat4x2.inl \
		/usr/local/include/glm/mat4x3.hpp \
		/usr/local/include/glm/detail/type_mat4x3.hpp \
		/usr/local/include/glm/detail/type_mat4x3.inl \
		/usr/local/include/glm/mat4x4.hpp \
		/usr/local/include/glm/detail/type_mat4x4.hpp \
		/usr/local/include/glm/detail/type_mat4x4.inl \
		/usr/local/include/glm/trigonometric.hpp \
		/usr/local/include/glm/detail/func_trigonometric.hpp \
		/usr/local/include/glm/detail/func_trigonometric.inl \
		/usr/local/include/glm/detail/_vectorize.hpp \
		/usr/local/include/glm/detail/type_vec1.hpp \
		/usr/local/include/glm/detail/type_vec1.inl \
		/usr/local/include/glm/exponential.hpp \
		/usr/local/include/glm/detail/func_exponential.hpp \
		/usr/local/include/glm/detail/func_exponential.inl \
		/usr/local/include/glm/detail/func_vector_relational.hpp \
		/usr/local/include/glm/detail/func_vector_relational.inl \
		/usr/local/include/glm/common.hpp \
		/usr/local/include/glm/detail/func_common.hpp \
		/usr/local/include/glm/detail/func_common.inl \
		/usr/local/include/glm/packing.hpp \
		/usr/local/include/glm/detail/func_packing.hpp \
		/usr/local/include/glm/detail/func_packing.inl \
		/usr/local/include/glm/detail/type_half.hpp \
		/usr/local/include/glm/detail/type_half.inl \
		/usr/local/include/glm/geometric.hpp \
		/usr/local/include/glm/detail/func_geometric.hpp \
		/usr/local/include/glm/detail/func_geometric.inl \
		/usr/local/include/glm/matrix.hpp \
		/usr/local/include/glm/detail/func_matrix.hpp \
		/usr/local/include/glm/detail/func_matrix.inl \
		/usr/local/include/glm/vector_relational.hpp \
		/usr/local/include/glm/integer.hpp \
		/usr/local/include/glm/detail/func_integer.hpp \
		/usr/local/include/glm/detail/func_integer.inl \
		/usr/local/include/glm/gtc/matrix_transform.hpp \
		/usr/local/include/glm/gtc/constants.hpp \
		/usr/local/include/glm/gtc/constants.inl \
		/usr/local/include/glm/gtc/matrix_transform.inl \
		/usr/local/include/glm/gtc/type_ptr.hpp \
		/usr/local/include/glm/gtc/quaternion.hpp \
		/usr/local/include/glm/gtc/quaternion.inl \
		/usr/local/include/glm/gtc/type_ptr.inl \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLWidget \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QEvent \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qcoreevent.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/QResizeEvent \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		include/mainwindow.h
	/Users/Toby/Qt5.2.1/5.2.1/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) include/mainwindow.h -o moc/moc_mainwindow.cpp

moc/moc_OpenGLWidget.cpp: include/Camera.h \
		/usr/local/include/glm/glm.hpp \
		/usr/local/include/glm/detail/_fixes.hpp \
		/usr/local/include/glm/fwd.hpp \
		/usr/local/include/glm/detail/type_int.hpp \
		/usr/local/include/glm/detail/setup.hpp \
		/usr/local/include/glm/detail/type_float.hpp \
		/usr/local/include/glm/detail/type_vec.hpp \
		/usr/local/include/glm/detail/precision.hpp \
		/usr/local/include/glm/detail/type_mat.hpp \
		/usr/local/include/glm/vec2.hpp \
		/usr/local/include/glm/detail/type_vec2.hpp \
		/usr/local/include/glm/detail/_swizzle.hpp \
		/usr/local/include/glm/detail/_swizzle_func.hpp \
		/usr/local/include/glm/detail/type_vec2.inl \
		/usr/local/include/glm/vec3.hpp \
		/usr/local/include/glm/detail/type_vec3.hpp \
		/usr/local/include/glm/detail/type_vec3.inl \
		/usr/local/include/glm/vec4.hpp \
		/usr/local/include/glm/detail/type_vec4.hpp \
		/usr/local/include/glm/detail/type_vec4.inl \
		/usr/local/include/glm/mat2x2.hpp \
		/usr/local/include/glm/detail/type_mat2x2.hpp \
		/usr/local/include/glm/detail/type_mat2x2.inl \
		/usr/local/include/glm/mat2x3.hpp \
		/usr/local/include/glm/detail/type_mat2x3.hpp \
		/usr/local/include/glm/detail/type_mat2x3.inl \
		/usr/local/include/glm/mat2x4.hpp \
		/usr/local/include/glm/detail/type_mat2x4.hpp \
		/usr/local/include/glm/detail/type_mat2x4.inl \
		/usr/local/include/glm/mat3x2.hpp \
		/usr/local/include/glm/detail/type_mat3x2.hpp \
		/usr/local/include/glm/detail/type_mat3x2.inl \
		/usr/local/include/glm/mat3x3.hpp \
		/usr/local/include/glm/detail/type_mat3x3.hpp \
		/usr/local/include/glm/detail/type_mat3x3.inl \
		/usr/local/include/glm/mat3x4.hpp \
		/usr/local/include/glm/detail/type_mat3x4.hpp \
		/usr/local/include/glm/detail/type_mat3x4.inl \
		/usr/local/include/glm/mat4x2.hpp \
		/usr/local/include/glm/detail/type_mat4x2.hpp \
		/usr/local/include/glm/detail/type_mat4x2.inl \
		/usr/local/include/glm/mat4x3.hpp \
		/usr/local/include/glm/detail/type_mat4x3.hpp \
		/usr/local/include/glm/detail/type_mat4x3.inl \
		/usr/local/include/glm/mat4x4.hpp \
		/usr/local/include/glm/detail/type_mat4x4.hpp \
		/usr/local/include/glm/detail/type_mat4x4.inl \
		/usr/local/include/glm/trigonometric.hpp \
		/usr/local/include/glm/detail/func_trigonometric.hpp \
		/usr/local/include/glm/detail/func_trigonometric.inl \
		/usr/local/include/glm/detail/_vectorize.hpp \
		/usr/local/include/glm/detail/type_vec1.hpp \
		/usr/local/include/glm/detail/type_vec1.inl \
		/usr/local/include/glm/exponential.hpp \
		/usr/local/include/glm/detail/func_exponential.hpp \
		/usr/local/include/glm/detail/func_exponential.inl \
		/usr/local/include/glm/detail/func_vector_relational.hpp \
		/usr/local/include/glm/detail/func_vector_relational.inl \
		/usr/local/include/glm/common.hpp \
		/usr/local/include/glm/detail/func_common.hpp \
		/usr/local/include/glm/detail/func_common.inl \
		/usr/local/include/glm/packing.hpp \
		/usr/local/include/glm/detail/func_packing.hpp \
		/usr/local/include/glm/detail/func_packing.inl \
		/usr/local/include/glm/detail/type_half.hpp \
		/usr/local/include/glm/detail/type_half.inl \
		/usr/local/include/glm/geometric.hpp \
		/usr/local/include/glm/detail/func_geometric.hpp \
		/usr/local/include/glm/detail/func_geometric.inl \
		/usr/local/include/glm/matrix.hpp \
		/usr/local/include/glm/detail/func_matrix.hpp \
		/usr/local/include/glm/detail/func_matrix.inl \
		/usr/local/include/glm/vector_relational.hpp \
		/usr/local/include/glm/integer.hpp \
		/usr/local/include/glm/detail/func_integer.hpp \
		/usr/local/include/glm/detail/func_integer.inl \
		/usr/local/include/glm/gtc/matrix_transform.hpp \
		/usr/local/include/glm/gtc/constants.hpp \
		/usr/local/include/glm/gtc/constants.inl \
		/usr/local/include/glm/gtc/matrix_transform.inl \
		/usr/local/include/glm/gtc/type_ptr.hpp \
		/usr/local/include/glm/gtc/quaternion.hpp \
		/usr/local/include/glm/gtc/quaternion.inl \
		/usr/local/include/glm/gtc/type_ptr.inl \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLWidget \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QEvent \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qcoreevent.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/QResizeEvent \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		include/OpenGLWidget.h
	/Users/Toby/Qt5.2.1/5.2.1/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) include/OpenGLWidget.h -o moc/moc_OpenGLWidget.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: ui/mainwindow.ui
	/Users/Toby/Qt5.2.1/5.2.1/clang_64/bin/uic ui/mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

obj/main.o: src/main.cpp /Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		include/mainwindow.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QToolBar \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbar.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QToolButton \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbutton.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDockWidget \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdockwidget.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenuBar \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QComboBox \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcombobox.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGridLayout \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgridlayout.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QSpacerItem \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlayoutitem.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QColorDialog \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolordialog.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPushButton \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDoubleSpinBox \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qspinbox.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGroupBox \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgroupbox.h \
		include/OpenGLWidget.h \
		include/Camera.h \
		/usr/local/include/glm/glm.hpp \
		/usr/local/include/glm/detail/_fixes.hpp \
		/usr/local/include/glm/fwd.hpp \
		/usr/local/include/glm/detail/type_int.hpp \
		/usr/local/include/glm/detail/setup.hpp \
		/usr/local/include/glm/detail/type_float.hpp \
		/usr/local/include/glm/detail/type_vec.hpp \
		/usr/local/include/glm/detail/precision.hpp \
		/usr/local/include/glm/detail/type_mat.hpp \
		/usr/local/include/glm/vec2.hpp \
		/usr/local/include/glm/detail/type_vec2.hpp \
		/usr/local/include/glm/detail/_swizzle.hpp \
		/usr/local/include/glm/detail/_swizzle_func.hpp \
		/usr/local/include/glm/detail/type_vec2.inl \
		/usr/local/include/glm/vec3.hpp \
		/usr/local/include/glm/detail/type_vec3.hpp \
		/usr/local/include/glm/detail/type_vec3.inl \
		/usr/local/include/glm/vec4.hpp \
		/usr/local/include/glm/detail/type_vec4.hpp \
		/usr/local/include/glm/detail/type_vec4.inl \
		/usr/local/include/glm/mat2x2.hpp \
		/usr/local/include/glm/detail/type_mat2x2.hpp \
		/usr/local/include/glm/detail/type_mat2x2.inl \
		/usr/local/include/glm/mat2x3.hpp \
		/usr/local/include/glm/detail/type_mat2x3.hpp \
		/usr/local/include/glm/detail/type_mat2x3.inl \
		/usr/local/include/glm/mat2x4.hpp \
		/usr/local/include/glm/detail/type_mat2x4.hpp \
		/usr/local/include/glm/detail/type_mat2x4.inl \
		/usr/local/include/glm/mat3x2.hpp \
		/usr/local/include/glm/detail/type_mat3x2.hpp \
		/usr/local/include/glm/detail/type_mat3x2.inl \
		/usr/local/include/glm/mat3x3.hpp \
		/usr/local/include/glm/detail/type_mat3x3.hpp \
		/usr/local/include/glm/detail/type_mat3x3.inl \
		/usr/local/include/glm/mat3x4.hpp \
		/usr/local/include/glm/detail/type_mat3x4.hpp \
		/usr/local/include/glm/detail/type_mat3x4.inl \
		/usr/local/include/glm/mat4x2.hpp \
		/usr/local/include/glm/detail/type_mat4x2.hpp \
		/usr/local/include/glm/detail/type_mat4x2.inl \
		/usr/local/include/glm/mat4x3.hpp \
		/usr/local/include/glm/detail/type_mat4x3.hpp \
		/usr/local/include/glm/detail/type_mat4x3.inl \
		/usr/local/include/glm/mat4x4.hpp \
		/usr/local/include/glm/detail/type_mat4x4.hpp \
		/usr/local/include/glm/detail/type_mat4x4.inl \
		/usr/local/include/glm/trigonometric.hpp \
		/usr/local/include/glm/detail/func_trigonometric.hpp \
		/usr/local/include/glm/detail/func_trigonometric.inl \
		/usr/local/include/glm/detail/_vectorize.hpp \
		/usr/local/include/glm/detail/type_vec1.hpp \
		/usr/local/include/glm/detail/type_vec1.inl \
		/usr/local/include/glm/exponential.hpp \
		/usr/local/include/glm/detail/func_exponential.hpp \
		/usr/local/include/glm/detail/func_exponential.inl \
		/usr/local/include/glm/detail/func_vector_relational.hpp \
		/usr/local/include/glm/detail/func_vector_relational.inl \
		/usr/local/include/glm/common.hpp \
		/usr/local/include/glm/detail/func_common.hpp \
		/usr/local/include/glm/detail/func_common.inl \
		/usr/local/include/glm/packing.hpp \
		/usr/local/include/glm/detail/func_packing.hpp \
		/usr/local/include/glm/detail/func_packing.inl \
		/usr/local/include/glm/detail/type_half.hpp \
		/usr/local/include/glm/detail/type_half.inl \
		/usr/local/include/glm/geometric.hpp \
		/usr/local/include/glm/detail/func_geometric.hpp \
		/usr/local/include/glm/detail/func_geometric.inl \
		/usr/local/include/glm/matrix.hpp \
		/usr/local/include/glm/detail/func_matrix.hpp \
		/usr/local/include/glm/detail/func_matrix.inl \
		/usr/local/include/glm/vector_relational.hpp \
		/usr/local/include/glm/integer.hpp \
		/usr/local/include/glm/detail/func_integer.hpp \
		/usr/local/include/glm/detail/func_integer.inl \
		/usr/local/include/glm/gtc/matrix_transform.hpp \
		/usr/local/include/glm/gtc/constants.hpp \
		/usr/local/include/glm/gtc/constants.inl \
		/usr/local/include/glm/gtc/matrix_transform.inl \
		/usr/local/include/glm/gtc/type_ptr.hpp \
		/usr/local/include/glm/gtc/quaternion.hpp \
		/usr/local/include/glm/gtc/quaternion.inl \
		/usr/local/include/glm/gtc/type_ptr.inl \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLWidget \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QEvent \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qcoreevent.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/QResizeEvent \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/mainwindow.o: src/mainwindow.cpp include/mainwindow.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QToolBar \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbar.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QToolButton \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbutton.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDockWidget \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdockwidget.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenuBar \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QComboBox \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcombobox.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGridLayout \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgridlayout.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QSpacerItem \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlayoutitem.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QColorDialog \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolordialog.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPushButton \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDoubleSpinBox \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qspinbox.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGroupBox \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgroupbox.h \
		include/OpenGLWidget.h \
		include/Camera.h \
		/usr/local/include/glm/glm.hpp \
		/usr/local/include/glm/detail/_fixes.hpp \
		/usr/local/include/glm/fwd.hpp \
		/usr/local/include/glm/detail/type_int.hpp \
		/usr/local/include/glm/detail/setup.hpp \
		/usr/local/include/glm/detail/type_float.hpp \
		/usr/local/include/glm/detail/type_vec.hpp \
		/usr/local/include/glm/detail/precision.hpp \
		/usr/local/include/glm/detail/type_mat.hpp \
		/usr/local/include/glm/vec2.hpp \
		/usr/local/include/glm/detail/type_vec2.hpp \
		/usr/local/include/glm/detail/_swizzle.hpp \
		/usr/local/include/glm/detail/_swizzle_func.hpp \
		/usr/local/include/glm/detail/type_vec2.inl \
		/usr/local/include/glm/vec3.hpp \
		/usr/local/include/glm/detail/type_vec3.hpp \
		/usr/local/include/glm/detail/type_vec3.inl \
		/usr/local/include/glm/vec4.hpp \
		/usr/local/include/glm/detail/type_vec4.hpp \
		/usr/local/include/glm/detail/type_vec4.inl \
		/usr/local/include/glm/mat2x2.hpp \
		/usr/local/include/glm/detail/type_mat2x2.hpp \
		/usr/local/include/glm/detail/type_mat2x2.inl \
		/usr/local/include/glm/mat2x3.hpp \
		/usr/local/include/glm/detail/type_mat2x3.hpp \
		/usr/local/include/glm/detail/type_mat2x3.inl \
		/usr/local/include/glm/mat2x4.hpp \
		/usr/local/include/glm/detail/type_mat2x4.hpp \
		/usr/local/include/glm/detail/type_mat2x4.inl \
		/usr/local/include/glm/mat3x2.hpp \
		/usr/local/include/glm/detail/type_mat3x2.hpp \
		/usr/local/include/glm/detail/type_mat3x2.inl \
		/usr/local/include/glm/mat3x3.hpp \
		/usr/local/include/glm/detail/type_mat3x3.hpp \
		/usr/local/include/glm/detail/type_mat3x3.inl \
		/usr/local/include/glm/mat3x4.hpp \
		/usr/local/include/glm/detail/type_mat3x4.hpp \
		/usr/local/include/glm/detail/type_mat3x4.inl \
		/usr/local/include/glm/mat4x2.hpp \
		/usr/local/include/glm/detail/type_mat4x2.hpp \
		/usr/local/include/glm/detail/type_mat4x2.inl \
		/usr/local/include/glm/mat4x3.hpp \
		/usr/local/include/glm/detail/type_mat4x3.hpp \
		/usr/local/include/glm/detail/type_mat4x3.inl \
		/usr/local/include/glm/mat4x4.hpp \
		/usr/local/include/glm/detail/type_mat4x4.hpp \
		/usr/local/include/glm/detail/type_mat4x4.inl \
		/usr/local/include/glm/trigonometric.hpp \
		/usr/local/include/glm/detail/func_trigonometric.hpp \
		/usr/local/include/glm/detail/func_trigonometric.inl \
		/usr/local/include/glm/detail/_vectorize.hpp \
		/usr/local/include/glm/detail/type_vec1.hpp \
		/usr/local/include/glm/detail/type_vec1.inl \
		/usr/local/include/glm/exponential.hpp \
		/usr/local/include/glm/detail/func_exponential.hpp \
		/usr/local/include/glm/detail/func_exponential.inl \
		/usr/local/include/glm/detail/func_vector_relational.hpp \
		/usr/local/include/glm/detail/func_vector_relational.inl \
		/usr/local/include/glm/common.hpp \
		/usr/local/include/glm/detail/func_common.hpp \
		/usr/local/include/glm/detail/func_common.inl \
		/usr/local/include/glm/packing.hpp \
		/usr/local/include/glm/detail/func_packing.hpp \
		/usr/local/include/glm/detail/func_packing.inl \
		/usr/local/include/glm/detail/type_half.hpp \
		/usr/local/include/glm/detail/type_half.inl \
		/usr/local/include/glm/geometric.hpp \
		/usr/local/include/glm/detail/func_geometric.hpp \
		/usr/local/include/glm/detail/func_geometric.inl \
		/usr/local/include/glm/matrix.hpp \
		/usr/local/include/glm/detail/func_matrix.hpp \
		/usr/local/include/glm/detail/func_matrix.inl \
		/usr/local/include/glm/vector_relational.hpp \
		/usr/local/include/glm/integer.hpp \
		/usr/local/include/glm/detail/func_integer.hpp \
		/usr/local/include/glm/detail/func_integer.inl \
		/usr/local/include/glm/gtc/matrix_transform.hpp \
		/usr/local/include/glm/gtc/constants.hpp \
		/usr/local/include/glm/gtc/constants.inl \
		/usr/local/include/glm/gtc/matrix_transform.inl \
		/usr/local/include/glm/gtc/type_ptr.hpp \
		/usr/local/include/glm/gtc/quaternion.hpp \
		/usr/local/include/glm/gtc/quaternion.inl \
		/usr/local/include/glm/gtc/type_ptr.inl \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLWidget \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QEvent \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qcoreevent.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/QResizeEvent \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		ui_mainwindow.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFileDialog \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QtWidgets \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaccessiblewidget.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qerrormessage.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfilesystemmodel.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfontdialog.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qinputdialog.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qprogressdialog.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwizard.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicseffect.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsanchorlayout.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsgridlayout.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsitem.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsitemanimation.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslayout.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslayoutitem.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslinearlayout.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsproxywidget.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsscene.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicssceneevent.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicstransform.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsview.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicswidget.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractitemdelegate.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractitemview.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolumnview.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdatawidgetmapper.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdirmodel.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfileiconprovider.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qheaderview.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qitemdelegate.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qitemeditorfactory.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistview.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistwidget.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleditemdelegate.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtableview.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreeview.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidgetitemiterator.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaction.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qactiongroup.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdesktopwidget.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qformlayout.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgesture.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgesturerecognizer.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlayout.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qshortcut.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsizepolicy.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstackedlayout.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtooltip.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwhatsthis.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidgetaction.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qkeyeventtransition.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmouseeventtransition.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcommonstyle.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdrawutil.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qproxystyle.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyle.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstylefactory.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleoption.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstylepainter.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleplugin.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolormap.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcompleter.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscroller.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscrollerproperties.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsystemtrayicon.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qundogroup.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qundostack.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qundoview.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractbutton.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractscrollarea.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractslider.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractspinbox.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qbuttongroup.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcalendarwidget.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcheckbox.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcommandlinkbutton.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdatetimeedit.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdial.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialogbuttonbox.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfocusframe.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfontcombobox.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qframe.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qkeysequenceedit.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlcdnumber.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlineedit.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmdiarea.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmdisubwindow.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qplaintextedit.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qprogressbar.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qradiobutton.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qrubberband.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscrollarea.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscrollbar.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsizegrip.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qslider.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsplashscreen.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsplitter.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstackedwidget.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstatusbar.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtabbar.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtabwidget.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextbrowser.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextedit.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbox.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtwidgetsversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/mainwindow.o src/mainwindow.cpp

obj/Camera.o: src/Camera.cpp include/Camera.h \
		/usr/local/include/glm/glm.hpp \
		/usr/local/include/glm/detail/_fixes.hpp \
		/usr/local/include/glm/fwd.hpp \
		/usr/local/include/glm/detail/type_int.hpp \
		/usr/local/include/glm/detail/setup.hpp \
		/usr/local/include/glm/detail/type_float.hpp \
		/usr/local/include/glm/detail/type_vec.hpp \
		/usr/local/include/glm/detail/precision.hpp \
		/usr/local/include/glm/detail/type_mat.hpp \
		/usr/local/include/glm/vec2.hpp \
		/usr/local/include/glm/detail/type_vec2.hpp \
		/usr/local/include/glm/detail/_swizzle.hpp \
		/usr/local/include/glm/detail/_swizzle_func.hpp \
		/usr/local/include/glm/detail/type_vec2.inl \
		/usr/local/include/glm/vec3.hpp \
		/usr/local/include/glm/detail/type_vec3.hpp \
		/usr/local/include/glm/detail/type_vec3.inl \
		/usr/local/include/glm/vec4.hpp \
		/usr/local/include/glm/detail/type_vec4.hpp \
		/usr/local/include/glm/detail/type_vec4.inl \
		/usr/local/include/glm/mat2x2.hpp \
		/usr/local/include/glm/detail/type_mat2x2.hpp \
		/usr/local/include/glm/detail/type_mat2x2.inl \
		/usr/local/include/glm/mat2x3.hpp \
		/usr/local/include/glm/detail/type_mat2x3.hpp \
		/usr/local/include/glm/detail/type_mat2x3.inl \
		/usr/local/include/glm/mat2x4.hpp \
		/usr/local/include/glm/detail/type_mat2x4.hpp \
		/usr/local/include/glm/detail/type_mat2x4.inl \
		/usr/local/include/glm/mat3x2.hpp \
		/usr/local/include/glm/detail/type_mat3x2.hpp \
		/usr/local/include/glm/detail/type_mat3x2.inl \
		/usr/local/include/glm/mat3x3.hpp \
		/usr/local/include/glm/detail/type_mat3x3.hpp \
		/usr/local/include/glm/detail/type_mat3x3.inl \
		/usr/local/include/glm/mat3x4.hpp \
		/usr/local/include/glm/detail/type_mat3x4.hpp \
		/usr/local/include/glm/detail/type_mat3x4.inl \
		/usr/local/include/glm/mat4x2.hpp \
		/usr/local/include/glm/detail/type_mat4x2.hpp \
		/usr/local/include/glm/detail/type_mat4x2.inl \
		/usr/local/include/glm/mat4x3.hpp \
		/usr/local/include/glm/detail/type_mat4x3.hpp \
		/usr/local/include/glm/detail/type_mat4x3.inl \
		/usr/local/include/glm/mat4x4.hpp \
		/usr/local/include/glm/detail/type_mat4x4.hpp \
		/usr/local/include/glm/detail/type_mat4x4.inl \
		/usr/local/include/glm/trigonometric.hpp \
		/usr/local/include/glm/detail/func_trigonometric.hpp \
		/usr/local/include/glm/detail/func_trigonometric.inl \
		/usr/local/include/glm/detail/_vectorize.hpp \
		/usr/local/include/glm/detail/type_vec1.hpp \
		/usr/local/include/glm/detail/type_vec1.inl \
		/usr/local/include/glm/exponential.hpp \
		/usr/local/include/glm/detail/func_exponential.hpp \
		/usr/local/include/glm/detail/func_exponential.inl \
		/usr/local/include/glm/detail/func_vector_relational.hpp \
		/usr/local/include/glm/detail/func_vector_relational.inl \
		/usr/local/include/glm/common.hpp \
		/usr/local/include/glm/detail/func_common.hpp \
		/usr/local/include/glm/detail/func_common.inl \
		/usr/local/include/glm/packing.hpp \
		/usr/local/include/glm/detail/func_packing.hpp \
		/usr/local/include/glm/detail/func_packing.inl \
		/usr/local/include/glm/detail/type_half.hpp \
		/usr/local/include/glm/detail/type_half.inl \
		/usr/local/include/glm/geometric.hpp \
		/usr/local/include/glm/detail/func_geometric.hpp \
		/usr/local/include/glm/detail/func_geometric.inl \
		/usr/local/include/glm/matrix.hpp \
		/usr/local/include/glm/detail/func_matrix.hpp \
		/usr/local/include/glm/detail/func_matrix.inl \
		/usr/local/include/glm/vector_relational.hpp \
		/usr/local/include/glm/integer.hpp \
		/usr/local/include/glm/detail/func_integer.hpp \
		/usr/local/include/glm/detail/func_integer.inl \
		/usr/local/include/glm/gtc/matrix_transform.hpp \
		/usr/local/include/glm/gtc/constants.hpp \
		/usr/local/include/glm/gtc/constants.inl \
		/usr/local/include/glm/gtc/matrix_transform.inl \
		/usr/local/include/glm/gtc/type_ptr.hpp \
		/usr/local/include/glm/gtc/quaternion.hpp \
		/usr/local/include/glm/gtc/quaternion.inl \
		/usr/local/include/glm/gtc/type_ptr.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Camera.o src/Camera.cpp

obj/OpenGLWidget.o: src/OpenGLWidget.cpp include/OpenGLWidget.h \
		include/Camera.h \
		/usr/local/include/glm/glm.hpp \
		/usr/local/include/glm/detail/_fixes.hpp \
		/usr/local/include/glm/fwd.hpp \
		/usr/local/include/glm/detail/type_int.hpp \
		/usr/local/include/glm/detail/setup.hpp \
		/usr/local/include/glm/detail/type_float.hpp \
		/usr/local/include/glm/detail/type_vec.hpp \
		/usr/local/include/glm/detail/precision.hpp \
		/usr/local/include/glm/detail/type_mat.hpp \
		/usr/local/include/glm/vec2.hpp \
		/usr/local/include/glm/detail/type_vec2.hpp \
		/usr/local/include/glm/detail/_swizzle.hpp \
		/usr/local/include/glm/detail/_swizzle_func.hpp \
		/usr/local/include/glm/detail/type_vec2.inl \
		/usr/local/include/glm/vec3.hpp \
		/usr/local/include/glm/detail/type_vec3.hpp \
		/usr/local/include/glm/detail/type_vec3.inl \
		/usr/local/include/glm/vec4.hpp \
		/usr/local/include/glm/detail/type_vec4.hpp \
		/usr/local/include/glm/detail/type_vec4.inl \
		/usr/local/include/glm/mat2x2.hpp \
		/usr/local/include/glm/detail/type_mat2x2.hpp \
		/usr/local/include/glm/detail/type_mat2x2.inl \
		/usr/local/include/glm/mat2x3.hpp \
		/usr/local/include/glm/detail/type_mat2x3.hpp \
		/usr/local/include/glm/detail/type_mat2x3.inl \
		/usr/local/include/glm/mat2x4.hpp \
		/usr/local/include/glm/detail/type_mat2x4.hpp \
		/usr/local/include/glm/detail/type_mat2x4.inl \
		/usr/local/include/glm/mat3x2.hpp \
		/usr/local/include/glm/detail/type_mat3x2.hpp \
		/usr/local/include/glm/detail/type_mat3x2.inl \
		/usr/local/include/glm/mat3x3.hpp \
		/usr/local/include/glm/detail/type_mat3x3.hpp \
		/usr/local/include/glm/detail/type_mat3x3.inl \
		/usr/local/include/glm/mat3x4.hpp \
		/usr/local/include/glm/detail/type_mat3x4.hpp \
		/usr/local/include/glm/detail/type_mat3x4.inl \
		/usr/local/include/glm/mat4x2.hpp \
		/usr/local/include/glm/detail/type_mat4x2.hpp \
		/usr/local/include/glm/detail/type_mat4x2.inl \
		/usr/local/include/glm/mat4x3.hpp \
		/usr/local/include/glm/detail/type_mat4x3.hpp \
		/usr/local/include/glm/detail/type_mat4x3.inl \
		/usr/local/include/glm/mat4x4.hpp \
		/usr/local/include/glm/detail/type_mat4x4.hpp \
		/usr/local/include/glm/detail/type_mat4x4.inl \
		/usr/local/include/glm/trigonometric.hpp \
		/usr/local/include/glm/detail/func_trigonometric.hpp \
		/usr/local/include/glm/detail/func_trigonometric.inl \
		/usr/local/include/glm/detail/_vectorize.hpp \
		/usr/local/include/glm/detail/type_vec1.hpp \
		/usr/local/include/glm/detail/type_vec1.inl \
		/usr/local/include/glm/exponential.hpp \
		/usr/local/include/glm/detail/func_exponential.hpp \
		/usr/local/include/glm/detail/func_exponential.inl \
		/usr/local/include/glm/detail/func_vector_relational.hpp \
		/usr/local/include/glm/detail/func_vector_relational.inl \
		/usr/local/include/glm/common.hpp \
		/usr/local/include/glm/detail/func_common.hpp \
		/usr/local/include/glm/detail/func_common.inl \
		/usr/local/include/glm/packing.hpp \
		/usr/local/include/glm/detail/func_packing.hpp \
		/usr/local/include/glm/detail/func_packing.inl \
		/usr/local/include/glm/detail/type_half.hpp \
		/usr/local/include/glm/detail/type_half.inl \
		/usr/local/include/glm/geometric.hpp \
		/usr/local/include/glm/detail/func_geometric.hpp \
		/usr/local/include/glm/detail/func_geometric.inl \
		/usr/local/include/glm/matrix.hpp \
		/usr/local/include/glm/detail/func_matrix.hpp \
		/usr/local/include/glm/detail/func_matrix.inl \
		/usr/local/include/glm/vector_relational.hpp \
		/usr/local/include/glm/integer.hpp \
		/usr/local/include/glm/detail/func_integer.hpp \
		/usr/local/include/glm/detail/func_integer.inl \
		/usr/local/include/glm/gtc/matrix_transform.hpp \
		/usr/local/include/glm/gtc/constants.hpp \
		/usr/local/include/glm/gtc/constants.inl \
		/usr/local/include/glm/gtc/matrix_transform.inl \
		/usr/local/include/glm/gtc/type_ptr.hpp \
		/usr/local/include/glm/gtc/quaternion.hpp \
		/usr/local/include/glm/gtc/quaternion.inl \
		/usr/local/include/glm/gtc/type_ptr.inl \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/QGLWidget \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QEvent \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qcoreevent.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/QResizeEvent \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/QGuiApplication \
		/Users/Toby/Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/qguiapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/OpenGLWidget.o src/OpenGLWidget.cpp

obj/moc_mainwindow.o: moc/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_mainwindow.o moc/moc_mainwindow.cpp

obj/moc_OpenGLWidget.o: moc/moc_OpenGLWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_OpenGLWidget.o moc/moc_OpenGLWidget.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

